JHJ/2606.cpp
=> [JHJ] 2606 문제 풀이

KSH/1697.cpp
문제 유형이 DFS BFS 라는걸 몰랐으면 못풀었을 것같아요
계속 메모리 초과가 나서 마지막엔 검색해봤는데 visited 처리를 안 해줬더라구요..
노드들을 입력하는 문제를 보다가 이런 새로운 문제를 접하니 DFS BFS에 대한 시각이 넓어지는 느낌입니다!
감사합니다~
=> 백준 1697번 문제입니다!

JHJ/11724.cpp
DFS, BFS를 통해서 연결된 그룹이 몇개인지 찾는 문제였습니다.
=> [JHJ] 11724 문제 풀이

KSH/1325.cpp
답이 잘 안나와서 검색해보았습니다. 
내일 문제는 꼭 맞춰보겠습니다 ㅎㅎ
=> 백준 1325번 문제

KSH/7576.cpp
x, y 입력 순서를 반대로 해서 한참 헤메고..
익은 토마토가 2개일 때 어떻게 해야할지 몰라서 검색해봤습니다!
=> 백준 7576번 문제

JHJ/7576.cpp
토마토 문제의 경우 BFS앞으로 많이 풀게 될 BFS 문제 유형에 속하는 대표적인 문제입니다.
물론 토마토가 살짝 어려운 편이라고 생각합니다.
- 4방향 움직임을 생각해야 한다는 점
- 움직일 때 거리를 생각해야 한다는 점
- 2차원 배열 사용
등등...
2차원 배열을 사용한 문제들이 대부분 토마토의 풀이 방법에서 조금씩 바뀐다고 생각하시면 됩니다!
그래서 이번 문제를 추천 문제로 둔 것이고 앞으로 BFS 문제 풀이를 하는데 좋은 경험이 되었으면 합니다!
=> [JHJ] 7576 문제 풀이

KSH/2667.cpp
맵 크기 받을 때 scanf를 안 써서 계속 틀리게 나와가지구 헤맸습니다 허허..
=> 백준 2667번 문제

JHJ/2667.cpp
BFS 를 통한 풀이를 진행했습니다.
DFS 로 풀어도 비슷한 풀이가 나왔을 것으로 보이고 어제 토마토 문제보다 손쉬운 문제일것으로 예상됩니다!
=> [JHJ] 2667 문제 풀이

KSH/10026.cpp
=> 백준 10026번 문제 

JHJ/10026.cpp
=> [JHJ] 10026 문제 풀이

KSH/2668.cpp
어떻게 풀어야 할지 막막했는데 DFS를 들이대보니 뭔가 해결법이 보이더라구요..!
문제 푸는게 재밌어집니다 스터디 너무 좋아요~
=> 백준 2668번 문제

KSH/13023.cpp
visited를 false로 다시 체크해주는 부분을 몰라서 검색해봤습니다!
백트래킹 문제는 생각할 부분이 많군요~
=> 백준 13023번 문제

KDH/[13023_ABCDE].cpp
N-1번 째 사람을 시작으로 모든 사람은 start node로 하여 DFS하면서
깊이가 4가 되면 true를 반환하여 끝내고 아니면 계속 확인하다가 false가 되는 방향으로 작성했는데,
틀렸네요 ㅜㅜ
=> 13023_ABCDE failed

JHJ/13023.cpp, JHJ/2668.cpp
DFS + 백트래킹 문제였습니다.
```cpp
void SearchFriend(int cur, int friendCount){
visit[cur] = true;
// 정답 확인 (아니면 return)
for(...]){
// 다음 지점으로 DFS
}
visit[cur] = false;  // 돌아와서 방문체크 해제하기! (중요!)
}
```
위와 같은 형태의 풀이들이 많이 나오게 되니 DFS + 백트래킹 문제 풀이할때 알아두시면 좋습니다!
=> [JHJ] 13023 문제 풀이

KSH/14500.cpp
이렇게 푸는게 아닐거같은데.. DFS나 BFS를 어떻게 활용해야 할지 모르겠네요 허허..
=> 백준 14500번 문제

JHJ/14500.cpp
해당 문제의 경우 여러가지 풀이가 있을 수 있습니다!
그렇기에 BFS, DFS 외에도 하드하게 풀이하는 방법 등 다양한 방법들이 있습니다.
DFS, BFS 로도 풀이를 할 수는 있는 문제라 이번에 넣었는데 그 외 방법으로 푸셔도 잘 하신겁니다!
일단 저의 경우 DFS 풀이를 진행했는데 이 방법은 하드한 방법에 비해서 시간은 오래 걸립니다. 시간이 276ms 나오거든요. (대부분 100 안으로)
다만 이 풀이의 장점은 코드가 간략하다! 라는게 있고 실제 코테에서도 이렇게 풀이를 했었습니다.
그리고 한 DFS만 잘 짰다면 예외사항을 고려하지 않아도 되는 장점이 있기도 합니다.
```cpp
for(int i = 0; i < 4; i++){
int nextY = y + moveY[i];
int nextX = x + moveX[i];
if(IsOut(nextY, nextX) || visit[nextY][nextX]) continue;
visit[nextY][nextX] = true;
GetSumFrom(nextY, nextX, count + 1, sum + map[nextY][nextX]);
GetSumFrom(y, x, count + 1, sum + map[nextY][nextX]);
visit[nextY][nextX] = false;
}
```
설명을 간단하게 드리면 위 DFS 과정에서 특이한게 재귀를 2가지로 불렀다는 점 입니다.
일단 처음 GetSumFrom의 경우에는 평범한 DFS 풀이법이고 아래 GetSumFrom은 ㅗ, ㅓ, ㅏ 같은 문제 풀이를 위한 것입니다.
ㅗ 탐색을 한다고 하면 중간 위를 탐색한 …
=> [JHJ] 14500 풀이

KSH/14226.cpp
으아니 문제는 되게 간단한데 안 풀려서 검색해봤습니다.
MAX값을 1000이 아니라 2000으로 두어야 입력을 1000으로 했을 때 결과가 나오는데 잘 이해가 안되네요 허허..
=> [KSH] 백준 14226번 문제

KSH/12851.cpp
안 풀려서 올려주신 코드랑 검색을 해봤습니다!
조금만 변형돼도 어렵네요 허허..ㅠ
=> [KSH] 백준 12851번 문제

JHJ/12851.cpp, JHJ/14226.cpp
이번 문제의 경우 2차원 배열을 visit 배열로 사용하는 문제입니다. 이런식으로 배열을 다차원으로 쓰는 경우가 있다와 이러한 식으로 '최단 횟수'를 구하는 방법은 BFS를 사용하는게 좋다! 라는걸 알고가면 좋은 문제입니다.
그리고 배열의 경우 이전에 제가 2001로 크기를 잡고 풀이를 했길래...이번에는 2가지로 해 봤습니다. 다만 2001로 하나 1001로 잡나 크게 차이가 없으며 오히려 1001로 잡아서 풀이한게 시간, 공간 복잡도가 줄어드는 모습을 볼 수 있었습니다.
아무래도 2001의 범위를 잡은게 '1000 넘게 그린 후 -1로 줄여가는게 빠른 경우'를 생각하지 않았나 하는데 1000의 범위로도 잘 되니 이런 경우는 없었나 봅니다...
=> [JHJ] 14226 문제 풀이

[1753_최단경로].cpp
무수한 시간초과 이후 혹시 몰라서 scanf, printf써봤는데 확실히 빠르네요.
처음으로 
```C++
cin.tie(NULL);
ios::sync_with_stdio(false);
```
이걸 써봤습니다.
p.s. : 주말동안 푸는걸 깜빡했습니다. 빠른 시일 내에 풀어서 올릴게요
=> 1753 solved

KSH/1753.cpp
오늘부터 다익스트라군요!
새로운 출발이네요 다음 문제가 기다려집니다 ㅎㅎ
=> [KSH] 백준 1753번 문제

KDH/[14284_간선이어가기2].cpp
=> 14284 solved

KSH/14284.cpp
=> [KSH] 백준 14284번 문제

JHJ/5972.CPP
말이 여물의 수지 사실상 비용을 의미하는 전형적인 다익스트라 문제입니다.
=> [JHJ] 5972 문제 풀이

KSH/5972.cpp
=> [KSH] 백준 5972번 문제

KDH/[4485_녹색옷을입은애가젤다지].cpp
=> feat : 4485 solved

JHJ/4485.cpp
1년 전 문제를 보니 입출력 가속을 안해서 4배 정도 느리긴 한데 워낙 입력값이 적어서 큰 차이는 없네요.
일단 이번 문제는 **BFS 처럼 생긴 다익스트라**문제입니다. 단순 BFS 로 하기에는 시간이 좀 많이 걸리고 각 칸으로 이동하는데 비용이 동일하지 않아서 다익스트라로 푸는게 훨씬 빠르게 나옵니다. 물론 while문 안에서 이를 순회하는 과정은 그냥 BFS와 비슷하지만요.
=> [JHJ] 4485 문제 풀이

KSH/4485.cpp
자꾸 pop하는걸 까먹어서 무한 루프를 돌게 되네요 허허
=> [KSH] 백준 4485번 문제

KHJ/14500.cpp
요즘 프로젝트 진행하느라 바쁘다 보니 너무 미루어지는 것 같아서 알고리즘 간만에 잡았습니다. 
일단 주어진 예제에 대한 부분들은 전부 통과가 되었는데 어째선지 실패하는군요..
이전에 설명해주신게 기억나서 ㅗ 모양만 돌아가서 체크해주는 별도의 함수 작성해주고 나머지는 회전이나 대칭이 이루어진다 하면 이어지는 깊이 값 체크라 되어야할텐데 왜 안되는지 모르겠군요
=> 14500 풀이 실패

KSH/1932.cpp
dp 첫 문제 제출합니다!
알고리즘 문제를 풀면 뭔가 뿌듯하네요 ㅎㅎ
=> [KSH] 백준 1932번 문제

JMS/2579.cpp
조건 빼면, 점화식은 아래와 같이 나올텐데, 
- 한 칸 뛰는 경우 : dp[i-1] + arr[i]
- 두 칸 뛰는 경우 : dp[i-2] + arr[i]
근데 연속으로 3칸 이동을 못하니 '한 칸' 뛰는 경우를 수정해줘야 합니다.
이전 계단에 도달하기 위해서는 무조건 2칸 뛰었다고 가정하는 겁니다. 그러면 i-3 계단의 최댓값과 이전 계단의 값을 더합니당,
- 수정된 한 칸 뛰는 경우 : arr[i-1] + dp[i-3] + arr[i]
※ dp는 최댓값이 담긴 배열, arr는 계단의 크기 배열
=> [JMS] 2579 번 문제풀이

KSH/2579.cpp
못풀어서 검색해봤습니다 허허..
3칸 연속으로 가지 못하는 걸 어떻게 dp를 사용해서 구현할지 감이 안 잡혔었는데 알고나니 굉장히 단순하네요!
다음 문제는 꼭 풀어보도록 하겠습니다~
=> [KSH] 백준 2579번 문제

KSH/11726.cpp
결국 오늘도 검색을.. 찾아보니 이렇게 간단할 수가 없네요!
규칙을 찾아내는 게 생각보다 쉽지 않군요
이전에 비슷한 문제를 분명 풀어봤던거같은데 다 까먹어버렸습니다 촤하하..
=> [KSH] 백준 11726번 문제

JMS/11726.cpp
는 못 풀어서 검색해봤습니다. ㅎ
해설을 보니 'n-2'일 때의 경우의 수가 "가로로 타일을 2개 붙이는 경우" 하나더군요..
저는 계속 "가로 타일 2개, 세로 타일 2개" 해서 경우의 수가 2개인줄 알았습니다.
이러면 n-1일 때와 겹친다는 생각을 못하고, 점화식을 못세웠네요..!
=> [JMS] 11726 번 문제풀이

KHJ/1149.cpp
음 조금씩 이제 감이 잡히는 것 같은데 여전히 어렵네요.
이 비용이 쌓인다는 것을 잘 생각하는게 중요할 것 같습니다.
여기서 느낀점은 다음 비용을 고려해서 진행하는게 아니라 이전의 비용을 생각해서 쌓아나가는 방식이 알맞는 것 같네요. 
이전 리뷰에 따라 인덱싱도 0 부터 시작하는 것으로 한번 바꾸어봤습니다.
=> [KHJ] 1149 풀이

KSH/1149.cpp
문제에 나온 입출력은 통과했지만 제출하면 틀려서 찾아봤습니다!
dp 배열을 1차원으로 사용했었는데 모든 경우를 고려하려면 2차원 배열로 해서 색깔별로 저장할 필요가 있었습니다.
점화식을 세우는게 생각보다 어렵네요 허허..
=> [KSH] 백준 1149번 문제

.vscode/settings.json, .vscode/tasks.json, JHJ/FirstTest/19539.cpp, JHJ/FirstTest/2343.cpp, JHJ/FirstTest/2961.cpp
=> [JHJ] 코테 1차 연습용 문제 풀이

KSH/12865.cpp
우아 이번문제는 해설을 보아도 어렵습니다..
dp 테이블 하나로 어떻게 무게와 최대가치를 모두 고려할 수 있을까 고민했는데..
dp[물건 번호][무게] = 최대가치
이렇게 할 수 있었네요! 오늘도 배워갑니다~
=> [KSH] 백준 12865번 문제

KHJ/12865.cpp, KHJ/2096.cpp
아 정말 어렵습니다... 해설을 보았는데도 애매하네요.
일단 각 무게나 가치를 동일한 배열 인덱스에 등록해서 for 문에서 max 기능을 활용해서 이전 DP 값이랑 비교해서 더 큰 값을 집어넣는데, 무게에 따라 이를 수행할지 안할지를 구분하는 조건문이 필요하다는 건 이해했는데 식이 이해가 안되네요..
=> [KHJ] 12865 못풀이

KHJ/11404.cpp
아 역시 한준님 말씀대로 푸는건 어렵지 않았습니다.
대신 주의할 점들이 꽤있더군요.
입력 값에서 이전 값을 덮어버리는걸 안막아서 값이 다르게 나온다던지, 높은 밸류값을 초기화 단계에서 넣어주는 것도 깜빡했었네요.
=> [KHJ] 11404 풀이

KSH/11404.cpp, KSH/12865.cpp
계속 3%에서 틀려가지구 찾아보았습니다.
이전 코드를 지우고 다시 쓰는 바람에 어떤부분이 다른지는 못찾았는데..
입력을 받는 부분에서 바로 계산을 할 수도 있다는 부분이 새로웠습니다!
=> [KSH] 백준 2096번 문제

KSH/11562.cpp, KSH/15723.cpp
어제 까먹고 안 풀어서 오늘 두 개 풀었습니다!
11562번은 어떻게 풀어야할지 막막했는데 검색해보니 가중치 그래프처럼 생각하면 된다는 힌트를 얻어서 풀었습니다..!
=> [KSH] 백준 15723번, 11562번 문제

KSH/2660.cpp
테이블 계산은 했는데 어떤식으로 회장을 찾아야 할지 몰라서 헤맸습니다. 
제가 잘 이해하고 푼 건지 모르겠네요 허헛..
=> [KSH] 백준 2660번 문제

KHJ/15723.cpp
이번에는 문자열이다보니 좀 어려웠습니다.
getline 이라는 함수도 알아보게 되었고 문자열 연산자 통해서 저렇게 인덱스값 반환받는 것도 알게되었네요. 여러모로 유익했습니다.
=> [KHJ] 15723 풀이

KSH/5582.cpp
기본 문제지만 맞추니까 기분이 너무 좋네요 허허허
굿 스타트!!
=> [KSH] 백준 5582번 문제

LS/11562.cpp, LS/2660.cpp, LS/5582.cpp
=> 2660, 5582

JMS/5582.cpp
=> [JMS] 5582 번 문제풀이

JHJ/5582.cpp
완전 LCS 기본 문제라서 다 비슷한 코드가 나올거라고 봅니다!
=> [JHJ] 5582 문제 풀이

KSH/9251.cpp
string의 size()를 int형에 담으니 계속 실패가 뜨더라구요. 
size() 자료형이 unsigned long이라서 다르다는 경고문구는 뜨긴했지만 
최대 문자열 길이가 1000자인데 왜 실패한건지 잘 모르겠습니다 훔..
=> [KSH] 백준 9251번 문제

KHJ/5582.cpp, KHJ/9251.cpp
재밌었습니다.
**[5582 문제]**
**[9251 문제]**
=> [KHJ] 5582, 9251 풀이

KSH/15482.cpp
한글로 하려면 3비트씩 읽으면 되는군요!
또 하나 배워갑니다 ㅎㅎ
=> [KSH] 백준 15482번 문제 

KSH/9252.cpp
저번 설명 때 들었던 거 생각하면서 풀어봤습니다!
오늘도 화이팅..!
=> [KSH] 백준 9252번 문제

JHJ/9252.cpp
=> [JHJ] 9252 문제 풀이

KHJ/15482.cpp, KHJ/9252.cpp
아까 한준님 풀이보면서 wstring 이라고 하셨길래 저도 wstring 해보려고 했더니 런타임 에러가 뜨네요... 
결국 유니코드상 표기되는 바이트 크기대로 쪼개서 확인하는 방법밖에 없는 것 같습니다.
=> [KHJ] 15482 풀이

JMS/1197.cpp, JMS/9252.cpp
가볍게 못 풀었습니다. String으로 계산해서 무거운듯 합니다. 
다른 풀이 보니까 기존과 동일하게 최장 수열 만들고, 역순으로 접근하여 문자열을 뽑아내더군요!
=> [JMS] 9252 번 문제풀이

KSH/1197.cpp
며칠 안 풀었다고 하마터면 푸는 걸 까먹을 뻔했습니다 허허..
MST 시작이네요! 퐈이팅~
=> [KSH] 백준 1197번 문제

KHJ/1197.cpp, KHJ/6497.cpp
어제 몸이 좀 안좋아서 이제 풀었네요...
정확히 한준님이 설명해주신대로 풀이하니 잘풀리는군요.
입력에서 조금 헤맸는데 무난히 잘풀린것 같습니다.
=> [KHJ] 1197 풀이

JMS/6497.cpp
이번에도 역시 간선의 개수가 더 많길래 프림 알고리즘을 사용해서 풀어봤습니다.
이전 문제와 비슷한거 같아요. 다음에는 크루스칼로 풀어봐야겠습니다.
※ 입력이 여러번 들어오는지 몰라서 좀 오래걸렸네요
=> [JMS] 6497 번 문제풀이

KSH/6497.cpp
오늘 문제 제출합니다~
이제 앞으로 한 문제 남았네요!
=> [KSH] 백준 6497번 문제

KSH/16398.cpp
마지막 문제 제출합니다!
입력받는 방법이 이전 문제들이랑 달라서 조금 헤맸지만 풀어서 기쁩니다 ㅎㅎ 
스터디하면서 많이 배워갑니다 감사합니다~!
=> [KSH] 백준 16398번 문제
